#### Redirects

[[redirects]]
from = "https://mavn.netlify.app"
to = "https://mavn.cf"
status = 301
force = true

#### Netlify Plugins

# Sitemap
[[plugins]]
package = "@netlify/plugin-sitemap"

[plugins.inputs]
prettyURLs = true
exclude = [
    "**/404.html"
]

# Submit Sitemap
[[plugins]]
package = "netlify-plugin-submit-sitemap"